language: cpp

env:
  global:
    - ICU_SRC_URL=https://github.com/unicode-org/icu/releases/download/release-67-1/icu4c-67_1-src.zip  # URL to .zip source release of ICU
    - ICU_WIN_URL=https://github.com/unicode-org/icu/releases/download/release-67-1/icu4c-67_1-Win64-MSVC2017.zip  # URL to .zip pre-built release of ICU for Windows x86_64

jobs:
  include:
    - name: "manylinux2014_aarch64"
      os: linux
      dist: focal
      arch: arm64
      services:
        - docker
      cache:
        directories:
          - ccache
      script:
        - docker run --rm -e CCACHE_DIR=/ccache -v $TRAVIS_BUILD_DIR/ccache:/ccache -v $(pwd):/iknow quay.io/pypa/manylinux2014_aarch64 /iknow/travis/build_manylinux.sh manylinux2014_aarch64 $ICU_SRC_URL $PYPI_TOKEN $TESTPYPI_TOKEN
        - travis/deploy_manylinux.sh
    - name: "manylinux2014_ppc64le"
      os: linux
      dist: focal
      arch: ppc64le
      services:
        - docker
      cache:
        directories:
          - ccache
      script:
        - docker run --rm -e CCACHE_DIR=/ccache -v $TRAVIS_BUILD_DIR/ccache:/ccache -v $(pwd):/iknow quay.io/pypa/manylinux2014_ppc64le /iknow/travis/build_manylinux.sh manylinux2014_ppc64le $ICU_SRC_URL $PYPI_TOKEN $TESTPYPI_TOKEN
        - travis/deploy_manylinux.sh
    - name: "manylinux2010_x86_64"
      os: linux
      dist: focal
      arch: amd64
      services:
        - docker
      cache:
        directories:
          - ccache
      script:
        - docker run --rm -e CCACHE_DIR=/ccache -v $TRAVIS_BUILD_DIR/ccache:/ccache -v $(pwd):/iknow quay.io/pypa/manylinux2010_x86_64 /iknow/travis/build_manylinux.sh manylinux2010_x86_64 $ICU_SRC_URL $PYPI_TOKEN $TESTPYPI_TOKEN
        - travis/deploy_manylinux.sh
    - name: "manylinux2010_i686"
      os: linux
      dist: focal
      arch: amd64
      services:
        - docker
      cache:
        directories:
          - ccache
      script:
        - docker run --rm -e CCACHE_DIR=/ccache -v $TRAVIS_BUILD_DIR/ccache:/ccache -v $(pwd):/iknow quay.io/pypa/manylinux2010_i686 linux32 /iknow/travis/build_manylinux.sh manylinux2010_i686 $ICU_SRC_URL $PYPI_TOKEN $TESTPYPI_TOKEN
        - travis/deploy_manylinux.sh
    - name: "Mac OS X 10.9 x86_64"
      os: osx
      osx_image: xcode11.6
      cache: ccache
      install:
        - export HOMEBREW_NO_AUTO_UPDATE=1
        - brew install ccache
        - export PATH="/usr/local/opt/ccache/libexec:$PATH"
        - travis/install_osx.sh
      script:
        - travis/build_osx.sh $ICU_SRC_URL $PYPI_TOKEN $TESTPYPI_TOKEN
        - ccache -s
    - name: "Windows x86_64"
      os: windows
      install:
        - travis/install_windows.sh
      script:
        - travis/build_windows.sh $ICU_WIN_URL $PYPI_TOKEN $TESTPYPI_TOKEN
