# Configuration for autoupdating dependencies.
#
# Once a day, at midnight UTC, we check for updates to
# - ICU
# - buildcache
# - Python for Windows
# - Python for Mac OS X
# - Cython
# - manylinux
#
# For each dependency that has an update, we create a pull request containing a
# single commit that updates the dependency.

name: Dependency Autoupdate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      BUILD_PULL_REQUEST:
        description: whether to build pull requests created by this workflow (1=yes, 0=no)
        required: true
        default: 1

jobs:
  autoupdate-ICU:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v2
      - name: search for update
        run: $GITHUB_WORKSPACE/actions/update_icu.py ${{ secrets.GITHUB_TOKEN }}
      - name: allow building pull requests
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 1
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST != 1
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        uses: peter-evans/create-pull-request@v3
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-ICU] update ICU from \"${{ env.ICU_NAME_OLD }}\" to \"${{ env.ICU_NAME_LATEST }}\""
          branch: autoupdate-ICU
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update ICU from \"${{ env.ICU_NAME_OLD }}\" to \"${{ env.ICU_NAME_LATEST }}\""
          body: |-
            As of ${{ env.ICU_PUBLISHED_AT }}, a new version of ICU has been released.

            Release Information (sourced from ${{ env.ICU_HTML_URL }})
            <blockquote>

            ${{ env.ICU_RELEASE_INFO }}
            </blockquote>

            *I am a bot, and this action was performed automatically.*

  autoupdate-buildcache:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v2
      - name: search for update
        run: $GITHUB_WORKSPACE/actions/update_buildcache.py ${{ secrets.GITHUB_TOKEN }}
      - name: allow building pull requests
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 1
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST != 1
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        uses: peter-evans/create-pull-request@v3
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-buildcache] update buildcache from \"${{ env.BUILDCACHE_NAME_OLD }}\" to \"${{ env.BUILDCACHE_NAME_LATEST }}\""
          branch: autoupdate-buildcache
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update buildcache from \"${{ env.BUILDCACHE_NAME_OLD }}\" to \"${{ env.BUILDCACHE_NAME_LATEST }}\""
          body: |-
            As of ${{ env.BUILDCACHE_PUBLISHED_AT }}, a new version of buildcache has been released.

            For details of the release, see ${{ env.BUILDCACHE_HTML_URL }}.

            *I am a bot, and this action was performed automatically.*

  autoupdate-cython:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v2
      - name: install Python packages
        run: pip3 install --user requests beautifulsoup4
      - name: search for update
        run: $GITHUB_WORKSPACE/actions/update_cython.py
      - name: allow building pull requests
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 1
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST != 1
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        uses: peter-evans/create-pull-request@v3
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-cython] update Cython from ${{ env.CYTHON_VERSION_OLD }} to ${{ env.CYTHON_VERSION_LATEST }}"
          branch: autoupdate-cython
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update Cython from ${{ env.CYTHON_VERSION_OLD }} to ${{ env.CYTHON_VERSION_LATEST }}"
          body: |-
            A new version of Cython is available.

            Changelog (sourced from https://cython.readthedocs.io/en/latest/src/changes.html)
            <blockquote>

            ${{ env.CYTHON_CHANGELOG }}
            </blockquote>

            *I am a bot, and this action was performed automatically.*

  autoupdate-manylinux:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v2
      - name: install Python packages
        run: pip3 install --user requests
      - name: search for update
        run: $GITHUB_WORKSPACE/actions/update_manylinux.py
      - name: allow building pull requests
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 1
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST != 1
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        uses: peter-evans/create-pull-request@v3
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-manylinux] update manylinux: ${{ env.MANYLINUX_UPDATE_INFO_ONELINE }}"
          branch: autoupdate-manylinux
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update manylinux: ${{ env.MANYLINUX_UPDATE_INFO_ONELINE }}"
          body: |-
            A new manylinux image is available.

            ${{ env.MANYLINUX_UPDATE_INFO_MULTILINE }}

            For details regarding manylinux images, see https://github.com/pypa/manylinux.

            *I am a bot, and this action was performed automatically.*

  autoupdate-python-windows:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v2
      - name: search for update
        run: $GITHUB_WORKSPACE/actions/update_python.py win64
      - name: allow building pull requests
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 1
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST != 1
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        uses: peter-evans/create-pull-request@v3
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-python-windows] update Python for Windows: ${{ env.PYTHON_UPDATE_INFO_ONELINE }}"
          branch: autoupdate-python-windows
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update Python for Windows: ${{ env.PYTHON_UPDATE_INFO_ONELINE }}"
          body: |-
            A new version of Python for Windows is available.

            ${{ env.PYTHON_UPDATE_INFO_MULTILINE }}

            For details of all Python releases, see https://www.nuget.org/packages/python.

            *I am a bot, and this action was performed automatically.*

  autoupdate-python-osx:
    runs-on: macos-10.15
    steps:
      - name: check out repository
        uses: actions/checkout@v2
      - name: search for update
        run: /usr/bin/python3 $GITHUB_WORKSPACE/actions/update_python.py osx
      - name: allow building pull requests
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 1
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST != 1
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        uses: peter-evans/create-pull-request@v3
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-python-osx] update Python for Mac OS X: ${{ env.PYTHON_UPDATE_INFO_ONELINE }}"
          branch: autoupdate-python-osx
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update Python for Mac OS X: ${{ env.PYTHON_UPDATE_INFO_ONELINE }}"
          body: |-
            A new version of Python for Mac OS X is available.

            ${{ env.PYTHON_UPDATE_INFO_MULTILINE }}

            For details of the updated versions, see https://github.com/pyenv/pyenv/releases/v${{ env.PYENV_TOOL_VERSION }}.

            *I am a bot, and this action was performed automatically.*
